spring.application.name=hiretrack
# DB Connection
spring.datasource.url=jdbc:mysql://localhost:3306/hiretrack_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Lava@2707

# Hibernate Settings
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl_auto=update